### ISSUE TITLE
pkg.ci.collectd.org is down

### ISSUE THREAD

**Issue by rfletcher** [collectd/collectd-ci#7]
http://pkg.ci.collectd.org has been down since at least Friday.

Aside: Is that meant to be used as an Apt source by the public? I was looking for up to date Ubuntu Collectd packages when I came across it.

**Comment by mfournier** [comment]
On Mon, Nov 02, 2015 at 07:24:21AM -0800, Rick Fletcher wrote:
> http://pkg.ci.collectd.org has been down since at least Friday.

Yes and no. There's an HSTS issue forcing modern browsers to bail out
because the service isn't available over https.

apt-get/yum/curl should work fine though.

> Aside: Is that meant to be used as a production Apt source by the public?
> I was looking for up to date Ubuntu Collectd packages when I cam across
> it.

Yes, please do. Just keep in mind these are built automatically out of the
tip of the project's git branches. So the packages typically change every
odd day.

If you are looking for a more "stable" solution for ubuntu, you might
prefer https://launchpad.net/~collectd/+archive/ubuntu/collectd-5.5

**Comment by rfletcher** [comment]
I wondered if it was normal not to be available in the browser, but saw that it was also offline in [Jenkins](https://ci.collectd.org) and took that as secondary evidence that it was actually down. Thanks for clearing that up, and for the launchpad link.
